[build]
command = "npm run build"
publish = "dist"
node_version = "18"

[build.environment]
VITE_FIREBASE_API_KEY = "AIzaSyBDUbJ7VSeUMwjTg1n8oT7GXiTZprhTjyE"
VITE_FIREBASE_AUTH_DOMAIN = "medisense-a6fea.firebaseapp.com"
VITE_FIREBASE_PROJECT_ID = "medisense-a6fea"
VITE_FIREBASE_STORAGE_BUCKET = "medisense-a6fea.firebasestorage.app"
VITE_FIREBASE_MESSAGING_SENDER_ID = "940057609553"
VITE_FIREBASE_APP_ID = "1:940057609553:web:733d6f51d39e93bf8fff70"
VITE_API_URL = "https://api.medisense.yourdomain.com"