name = "my-backend"
    main = "worker.js"
    compatibility_date = "2023-01-01"

    [vars]
    MONGODB_DATA_API_KEY = "your-mongodb-data-api-key"
    MONGODB_DATA_SOURCE = "your-mongodb-data-source"

    [[d1_databases]]
    binding = "MEDISENSE_D1"
    database_name = "medisense_d1"
    database_id = "8adb4d6c-7092-456a-8ec4-d8889e0abe1a"

    migrations_dir = "./"
